<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/master/M2C2%20Pandas_DataFrame_Essentials_Beginner_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas DataFrame Essentials

## Beginner-Friendly Hands-on Notebook

In this notebook, we will learn:

- What Pandas is
- What a DataFrame is
- How to import datasets
- How to inspect datasets
- How to select rows and columns
- How to filter useful data

## Step 1: Import Pandas

In [ ]:

import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!


## Step 2: Creating a Simple DataFrame

In [ ]:

data = {
    "Name": ["Harsha", "Rahul", "Sneha", "Aman"],
    "Age": [24, 25, 23, 26],
    "Marks": [88, 76, 91, 67]
}

df = pd.DataFrame(data)

df

     Name  Age  Marks
0  Harsha   24     88
1   Rahul   25     76
2   Sneha   23     91
3    Aman   26     67


## Step 3: Understanding Rows and Columns

In [ ]:

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (4, 3)
Columns: ['Name', 'Age', 'Marks']


## Step 4: Creating and Loading External Dataset

In [ ]:

sample_data = pd.DataFrame({
    "Employee": ["Amit", "Priya", "John", "Kiran", "Sara"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [45000, 70000, 65000, 72000, 50000]
})

sample_data.to_csv("employees.csv", index=False)

print("CSV File Created")

CSV File Created

In [ ]:

employees_df = pd.read_csv("employees.csv")

employees_df

  Employee Department  Salary
0     Amit         HR   45000
1    Priya         IT   70000
2     John    Finance   65000
3    Kiran         IT   72000
4     Sara  Marketing   50000


## Step 5: Initial Data Inspection

In [ ]:

employees_df.head()

  Employee Department  Salary
0     Amit         HR   45000
1    Priya         IT   70000
2     John    Finance   65000
3    Kiran         IT   72000
4     Sara  Marketing   50000

In [ ]:

employees_df.tail()

  Employee Department  Salary
0     Amit         HR   45000
1    Priya         IT   70000
2     John    Finance   65000
3    Kiran         IT   72000
4     Sara  Marketing   50000

In [ ]:

employees_df.shape

(5, 3)

In [ ]:

employees_df.columns

Index(['Employee', 'Department', 'Salary'], dtype='object')

In [ ]:

employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    5 non-null      object
 1   Department  5 non-null      object
 2   Salary      5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:

employees_df.describe()

             Salary
count      5.000000
mean   60400.000000
std    12177.848743
min    45000.000000
25%    50000.000000
50%    65000.000000
75%    70000.000000
max    72000.000000


## Step 6: Selecting Columns

In [ ]:

employees_df["Employee"]

In [ ]:

employees_df[["Employee", "Salary"]]


## Step 7: Accessing Rows

In [ ]:

employees_df.loc[0]

In [ ]:

employees_df.loc[0:2]


## Step 8: Filtering Data

In [ ]:

employees_df[employees_df["Salary"] > 60000]

In [ ]:

employees_df[employees_df["Department"] == "IT"]


## Step 9: Missing Values Awareness

In [ ]:

employees_df.isnull().sum()


# Mini Practice Tasks

1. Create your own student dataset
2. Display first 3 rows
3. Select marks column
4. Filter students scoring above 80
5. Display total rows and columns


# Final Takeaways

You learned:

- What Pandas DataFrames are
- How to load datasets
- How to inspect data
- How to select useful information
- Basic industry workflow in Pandas