<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/master/M2C2%20Data_Cleaning_Missing_Value_Treatment_Beginner_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning and Missing Value Treatment

## Beginner-Friendly Hands-on Notebook

In real-world data, we often see:

- Empty values
- Wrong data formats
- Extra spaces in text
- Dates stored as text
- Numbers stored as text

In this notebook, we will learn how to identify and fix these basic issues using Pandas.

### What you will learn

1. How to find missing values
2. How to treat missing values
3. How to convert data formats
4. How to validate cleaned data
5. How to build a simple data cleaning workflow

## 1. Import Pandas

Pandas helps us work with tabular data, similar to Excel sheets.

In [ ]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

## 2. Create a Small Messy Dataset

We will create a small employee dataset with common real-world problems:

- Missing values
- Salary stored as text
- Dates stored as text
- Extra spaces
- Inconsistent capitalization

In [ ]:
data = {
    "employee_id": [101, 102, 103, 104, 105, 106, 107],
    "name": ["Amit", "Priya", "John", "Kiran", "Sara", "Meena", "Ravi"],
    "department": ["IT", " HR", None, "Finance", "it", "Marketing", None],
    "age": [25, None, 30, 28, None, 32, 26],
    "salary": ["₹45,000", "₹52,000", None, "₹60,000", "₹48,000", "not available", "₹50,000"],
    "joining_date": ["2023-01-15", "2022/03/10", "15-04-2021", None, "2023-07-01", "Invalid Date", "2022-11-20"],
    "city": ["Bangalore", " hyderabad", "Mumbai", None, "bangalore", "Delhi ", "Chennai"]
}

df = pd.DataFrame(data)

df

,employee_id,name,department,age,salary,joining_date,city
0,101,Amit,IT,25.0,"₹45,000",2023-01-15,Bangalore
1,102,Priya,HR,NaN,"₹52,000",2022/03/10,hyderabad
2,103,John,None,30.0,None,15-04-2021,Mumbai
3,104,Kiran,Finance,28.0,"₹60,000",None,None
4,105,Sara,it,NaN,"₹48,000",2023-07-01,bangalore
5,106,Meena,Marketing,32.0,not available,Invalid Date,Delhi
6,107,Ravi,None,26.0,"₹50,000",2022-11-20,Chennai

## 3. Initial Data Inspection

Before cleaning, we first inspect the dataset.

Think of this like checking a room before cleaning it.

In [ ]:
# First five rows
df.head()

   employee_id   name department   age   salary joining_date        city
0          101   Amit         IT  25.0  ₹45,000   2023-01-15   Bangalore
1          102  Priya         HR   NaN  ₹52,000   2022/03/10   hyderabad
2          103   John       None  30.0     None   15-04-2021      Mumbai
3          104  Kiran    Finance  28.0  ₹60,000         None        None
4          105   Sara         it   NaN  ₹48,000   2023-07-01   bangalore

In [ ]:
# Number of rows and columns
df.shape

(7, 7)

In [ ]:
# Basic information about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   employee_id   7 non-null      int64
 1   name          7 non-null      object
 2   department    5 non-null      object
 3   age           5 non-null      float64
 4   salary        6 non-null      object
 5   joining_date  6 non-null      object
 6   city          6 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 524.0+ bytes

## 4. Identify Missing Values

Missing values usually appear as `NaN` or `None`.

In industry, this step is important because missing data can affect reports, dashboards, and ML models.

In [ ]:
# True means value is missing
df.isnull()

   employee_id   name  department    age  salary  joining_date   city
0        False  False       False  False   False         False  False
1        False  False       False   True   False         False  False
2        False  False        True  False    True         False  False
3        False  False       False  False   False          True   True
4        False  False       False   True   False         False  False
5        False  False       False  False   False         False  False
6        False  False        True  False   False         False  False

In [ ]:
# Count missing values in each column
df.isnull().sum()

employee_id     0
name            0
department      2
age             2
salary          1
joining_date    1
city            1
dtype: int64

In [ ]:
# Percentage of missing values in each column
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage

employee_id      0.000000
name             0.000000
department      28.571429
age             28.571429
salary          14.285714
joining_date    14.285714
city            14.285714
dtype: float64

## 5. Understand Missing Value Treatment

There is no single perfect method for all missing values.

Simple beginner-friendly rules:

- If very few rows are missing, sometimes we can drop them.
- For numerical columns like age or salary, we can fill with mean or median.
- For text/category columns like department or city, we can fill with mode or `Unknown`.

For this session, we will use simple industry-friendly beginner methods.

## 6. Treat Missing Values in Text Columns

For columns like department and city, we will fill missing values with `Unknown`.

In [ ]:
df["department"] = df["department"].fillna("Unknown")
df["city"] = df["city"].fillna("Unknown")

df[["department", "city"]]

  department        city
0         IT   Bangalore
1         HR   hyderabad
2    Unknown      Mumbai
3    Finance     Unknown
4         it   bangalore
5  Marketing      Delhi
6    Unknown     Chennai

## 7. Treat Missing Values in Numeric Columns

The `age` column is numeric. We can fill missing age values using the median age.

Median is often preferred when we want a stable middle value.

In [ ]:
median_age = df["age"].median()
print("Median age:", median_age)

df["age"] = df["age"].fillna(median_age)

df[["name", "age"]]

Median age: 28.0

    name   age
0   Amit  25.0
1  Priya  28.0
2   John  30.0
3  Kiran  28.0
4   Sara  28.0
5  Meena  32.0
6   Ravi  26.0

## 8. Data Format Conversion: Salary Cleaning

The salary column currently contains values like `₹45,000`, so Pandas treats it as text.

Before calculations, we must convert it into numbers.

In [ ]:
# Check current salary values
df["salary"]

0          ₹45,000
1          ₹52,000
2             None
3          ₹60,000
4          ₹48,000
5    not available
6          ₹50,000
Name: salary, dtype: object

In [ ]:
# Remove currency symbol and comma, then convert to numeric
df["salary_cleaned"] = (
    df["salary"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["salary_cleaned"] = pd.to_numeric(df["salary_cleaned"], errors="coerce")

df[["salary", "salary_cleaned"]]

          salary  salary_cleaned
0        ₹45,000         45000.0
1        ₹52,000         52000.0
2           None             NaN
3        ₹60,000         60000.0
4        ₹48,000         48000.0
5  not available             NaN
6        ₹50,000         50000.0

### Why `errors="coerce"`?

If a value cannot be converted into a number, Pandas converts it into `NaN`.

Example: `not available` cannot become a number, so it becomes missing.

In [ ]:
# Check missing values after salary conversion
df["salary_cleaned"].isnull().sum()

np.int64(2)

## 9. Fill Missing Salary Values

Now we can fill missing salary values using the median salary.

In [ ]:
median_salary = df["salary_cleaned"].median()
print("Median salary:", median_salary)

df["salary_cleaned"] = df["salary_cleaned"].fillna(median_salary)

df[["name", "salary", "salary_cleaned"]]

Median salary: 50000.0

    name         salary  salary_cleaned
0   Amit        ₹45,000         45000.0
1  Priya        ₹52,000         52000.0
2   John           None         50000.0
3  Kiran        ₹60,000         60000.0
4   Sara        ₹48,000         48000.0
5  Meena  not available         50000.0
6   Ravi        ₹50,000         50000.0

## 10. Data Format Conversion: Date Cleaning

Dates are often stored in different formats.

We will convert the `joining_date` column into a proper datetime format.

In [ ]:
df["joining_date_cleaned"] = pd.to_datetime(df["joining_date"], errors="coerce", dayfirst=True)

df[["joining_date", "joining_date_cleaned"]]

/tmp/ipykernel_10147/3823716736.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["joining_date_cleaned"] = pd.to_datetime(df["joining_date"], errors="coerce", dayfirst=True)

   joining_date joining_date_cleaned
0    2023-01-15           2023-01-15
1    2022/03/10                  NaT
2    15-04-2021                  NaT
3          None                  NaT
4    2023-07-01           2023-07-01
5  Invalid Date                  NaT
6    2022-11-20           2022-11-20

Invalid or missing dates become `NaT`, which means missing datetime value.

In [ ]:
df["joining_date_cleaned"].isnull().sum()

np.int64(4)

For this beginner session, we will fill missing dates with a placeholder date.

In real projects, the right treatment depends on business context.

In [ ]:
df["joining_date_cleaned"] = df["joining_date_cleaned"].fillna(pd.to_datetime("1900-01-01"))

df[["name", "joining_date_cleaned"]]

    name joining_date_cleaned
0   Amit           2023-01-15
1  Priya           1900-01-01
2   John           1900-01-01
3  Kiran           1900-01-01
4   Sara           2023-07-01
5  Meena           1900-01-01
6   Ravi           2022-11-20

## 11. Basic Text Cleaning

Text columns may have:

- Extra spaces
- Different capitalization
- Same value written in different ways

Example: `IT`, `it`, and ` IT` should be treated consistently.

In [ ]:
df["department_cleaned"] = df["department"].astype(str).str.strip().str.title()
df["city_cleaned"] = df["city"].astype(str).str.strip().str.title()

df[["department", "department_cleaned", "city", "city_cleaned"]]

  department department_cleaned        city city_cleaned
0         IT                 It   Bangalore    Bangalore
1         HR                 Hr   hyderabad    Hyderabad
2    Unknown            Unknown      Mumbai       Mumbai
3    Finance            Finance     Unknown      Unknown
4         it                 It   bangalore    Bangalore
5  Marketing          Marketing      Delhi         Delhi
6    Unknown            Unknown     Chennai      Chennai

## 12. Convert Age to Integer

After filling missing values, we can convert age from float to integer.

In [ ]:
df["age"] = df["age"].astype(int)

df[["name", "age"]]

## 13. Create Final Cleaned Dataset

Now we will keep only useful cleaned columns.

In [ ]:
cleaned_df = df[[
    "employee_id",
    "name",
    "department_cleaned",
    "age",
    "salary_cleaned",
    "joining_date_cleaned",
    "city_cleaned"
]]

cleaned_df = cleaned_df.rename(columns={
    "department_cleaned": "department",
    "salary_cleaned": "salary",
    "joining_date_cleaned": "joining_date",
    "city_cleaned": "city"
})

cleaned_df

## 14. Validate the Cleaned Dataset

After cleaning, always validate.

Basic validation checklist:

- Are missing values handled?
- Are data types correct?
- Does the dataset look clean?
- Can we perform calculations?

In [ ]:
# Check missing values again
cleaned_df.isnull().sum()

In [ ]:
# Check final data types
cleaned_df.info()

In [ ]:
# Can we calculate average salary now?
average_salary = cleaned_df["salary"].mean()
print("Average Salary:", average_salary)

In [ ]:
# Can we calculate average age now?
average_age = cleaned_df["age"].mean()
print("Average Age:", average_age)

## 15. Mini Practice Task

Try this with the dataset below.

Tasks:

1. Create the DataFrame
2. Find missing values
3. Fill missing product category with `Unknown`
4. Convert price to numeric
5. Fill missing price with median price
6. Convert order date to datetime
7. Validate the cleaned dataset

In [ ]:
practice_data = {
    "order_id": [1, 2, 3, 4, 5],
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones"],
    "category": ["Electronics", None, "Accessories", " Electronics ", None],
    "price": ["₹55,000", "₹700", None, "₹12,000", "not available"],
    "order_date": ["2024-01-10", "11/02/2024", None, "Invalid Date", "2024-03-15"]
}

practice_df = pd.DataFrame(practice_data)
practice_df

### Practice Solution

In [ ]:
# 1. Check missing values
practice_df.isnull().sum()

In [ ]:
# 2. Clean category
practice_df["category"] = practice_df["category"].fillna("Unknown")
practice_df["category"] = practice_df["category"].astype(str).str.strip().str.title()

# 3. Clean price and convert to numeric
practice_df["price_cleaned"] = (
    practice_df["price"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)
practice_df["price_cleaned"] = pd.to_numeric(practice_df["price_cleaned"], errors="coerce")

# 4. Fill missing price with median
practice_df["price_cleaned"] = practice_df["price_cleaned"].fillna(practice_df["price_cleaned"].median())

# 5. Convert order_date to datetime
practice_df["order_date_cleaned"] = pd.to_datetime(practice_df["order_date"], errors="coerce", dayfirst=True)

practice_df

In [ ]:
# Final validation
practice_df.info()
print("\nMissing values after cleaning:")
print(practice_df.isnull().sum())

# Final Takeaways

A simple data cleaning workflow is:

1. Inspect the dataset
2. Identify missing values
3. Treat missing values based on column meaning
4. Convert data into correct formats
5. Clean text inconsistencies
6. Validate the final dataset

This is one of the most important foundations for Data Analytics and Machine Learning.