<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/master/M2C4%20Advanced_Data_Selection_Filtering_Beginner_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Advanced Data Selection and Filtering

## Beginner-Friendly Hands-on Notebook

Topics covered:

- Selecting rows and columns
- Applying filters
- Using logical conditions
- Sorting data
- Reordering information

## Step 1: Import Pandas

In [ ]:

import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

## Step 2: Create Dataset

In [ ]:

data = {
    "Employee": ["Amit", "Priya", "John", "Kiran", "Sara", "Ravi"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing", "HR"],
    "Salary": [45000, 70000, 65000, 72000, 50000, 48000],
    "Experience": [2, 5, 4, 6, 3, 1]
}

df = pd.DataFrame(data)

df

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1    Priya         IT   70000           5
2     John    Finance   65000           4
3    Kiran         IT   72000           6
4     Sara  Marketing   50000           3
5     Ravi         HR   48000           1

## Step 3: Selecting Columns

In [ ]:

df["Employee"]

0     Amit
1    Priya
2     John
3    Kiran
4     Sara
5     Ravi
Name: Employee, dtype: object

In [ ]:

df[["Employee", "Salary"]]

  Employee  Salary
0     Amit   45000
1    Priya   70000
2     John   65000
3    Kiran   72000
4     Sara   50000
5     Ravi   48000

## Step 4: Selecting Rows

In [ ]:

df.loc[0]

Employee       Amit
Department       HR
Salary        45000
Experience        2
Name: 0, dtype: object

In [ ]:

df.loc[0:2]

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
1    Priya         IT   70000           5
2     John    Finance   65000           4

## Step 5: Filtering Data

In [ ]:

df[df["Salary"] > 60000]

  Employee Department  Salary  Experience
1    Priya         IT   70000           5
2     John    Finance   65000           4
3    Kiran         IT   72000           6

In [ ]:

df[df["Department"] == "IT"]

  Employee Department  Salary  Experience
1    Priya         IT   70000           5
3    Kiran         IT   72000           6

## Step 6: Multiple Conditions

In [ ]:

df[(df["Salary"] > 50000) & (df["Experience"] > 3)]

  Employee Department  Salary  Experience
1    Priya         IT   70000           5
2     John    Finance   65000           4
3    Kiran         IT   72000           6

In [ ]:

df[(df["Department"] == "HR") | (df["Department"] == "Marketing")]

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
4     Sara  Marketing   50000           3
5     Ravi         HR   48000           1

## Step 7: Sorting Data

In [ ]:

df.sort_values(by="Salary")

  Employee Department  Salary  Experience
0     Amit         HR   45000           2
5     Ravi         HR   48000           1
4     Sara  Marketing   50000           3
2     John    Finance   65000           4
1    Priya         IT   70000           5
3    Kiran         IT   72000           6

In [ ]:

df.sort_values(by="Salary", ascending=False)

  Employee Department  Salary  Experience
3    Kiran         IT   72000           6
1    Priya         IT   70000           5
2     John    Finance   65000           4
4     Sara  Marketing   50000           3
5     Ravi         HR   48000           1
0     Amit         HR   45000           2

In [ ]:

df.sort_values(by=["Department", "Salary"])

  Employee Department  Salary  Experience
2     John    Finance   65000           4
0     Amit         HR   45000           2
5     Ravi         HR   48000           1
1    Priya         IT   70000           5
3    Kiran         IT   72000           6
4     Sara  Marketing   50000           3

## Step 8: Reordering Columns

In [ ]:

df[["Department", "Employee", "Salary", "Experience"]]

  Department Employee  Salary  Experience
0         HR     Amit   45000           2
1         IT    Priya   70000           5
2    Finance     John   65000           4
3         IT    Kiran   72000           6
4  Marketing     Sara   50000           3
5         HR     Ravi   48000           1


# Mini Practice Tasks

1. Filter employees with salary above 50000
2. Filter employees with experience greater than 2
3. Sort employees by experience
4. Display only Employee and Department columns
5. Apply two conditions together


# Final Takeaways

You learned:

- Data filtering
- Logical conditions
- Sorting data
- Reordering information