<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/module3/M3C4%20Feature%20Engineering%20Strategies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Feature Engineering

In [ ]:
#House Price Prediction --> Regression
Features --> independent variables
1- area -sqft
2- BHK?
3 - Age of the building
4 - Locality
5 - Pool
6 - Guarded society
7 - Aminities - gym, etc


Target variable --> dependent variable
Selling price.

In [ ]:
Eg1:

DOB --> age = 2026 - DOB


Eg2:

Customer name, Total orders, Total revenue

New feature = Avg_order_value = total_revenue / total_orders --> feature engineering

Why we need feature engineering?
A simple model with good features often outperforms a complex model with poor features

#Feature Scaling

In [ ]:
# Why scaling --> distance based algorithms might often give more importance to higher value featrues (salary in this case)

# Age     Salary
# 25      250000
# 28      350000

# 1. Min-Max Scaling
# 2. Standard Scaling

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Age":[20,30,40],
    "Salary":[30000,50000,100000]
})

df

   Age  Salary
0   20   30000
1   30   50000
2   40  100000

#Min-Max Scaling

In [ ]:
# x --> (x - min)/(max - min) --> always ranges between 0 to 1

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

salary = pd.DataFrame({
    "Salary":[30000,50000,100000]
})
salary

   Salary
0   30000
1   50000
2  100000

In [ ]:
sc = MinMaxScaler()
df["Scaled_salary"] = sc.fit_transform(df[["Salary"]])
df

   Age  Salary  Scaled_salary
0   20   30000       0.000000
1   30   50000       0.285714
2   40  100000       1.000000

In [ ]:
(50000 - 30000)/(100000-30000)

0.2857142857142857

#Standard Scaling

In [ ]:
# x --> (x - mean)/std --> Mean = 0, Std = 1

In [ ]:
from sklearn.preprocessing import StandardScaler

s_sc = StandardScaler()

df["std_scaled_salary"] = s_sc.fit_transform(df[["Salary"]])
df

   Age  Salary  Scaled_salary  std_scaled_salary
0   20   30000       0.000000          -1.019049
1   30   50000       0.285714          -0.339683
2   40  100000       1.000000           1.358732

#Creating more predictive features

In [ ]:
# eg: 1
# salary , years_of_exp  --> salary/years_of_exp

# orders, revenue --> reveue/order

# dob , curr-year--> age = curr_yr - dob

In [ ]:
df = pd.DataFrame({
    "Age":[18,25,35,50,65]
})

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,15,30,60,100],
    labels=["Teen","Young","Adult","Senior"]
)

df

   Age Age_Group
0   18     Young
1   25     Young
2   35     Adult
3   50     Adult
4   65    Senior

#Date realted feature engineering

In [ ]:
df = pd.DataFrame({
    "Order_Date":[
        "2024-01-15",
        "2024-03-20"
    ]
})

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df

  Order_Date
0 2024-01-15
1 2024-03-20

In [ ]:
df["year"] = df["Order_Date"].dt.year
df

  Order_Date  year
0 2024-01-15  2024
1 2024-03-20  2024

In [ ]:
df["month"] = df["Order_Date"].dt.month
df

  Order_Date  year  month
0 2024-01-15  2024      1
1 2024-03-20  2024      3

In [ ]:
df["day"] = df["Order_Date"].dt.day
df

  Order_Date  year  month  day
0 2024-01-15  2024      1   15
1 2024-03-20  2024      3   20

In [ ]:
df["Weekday"] = df["Order_Date"].dt.day_of_week
df

  Order_Date  year  month  day  Weekday
0 2024-01-15  2024      1   15        0
1 2024-03-20  2024      3   20        2

In [ ]:
# is_weekend? 0-> monday

df["is_weekend"] = pd.cut(
    df["Weekday"],
    bins=[-1,5,7],
    labels=["No", "Yes"]
)

df

  Order_Date  year  month  day  Weekday is_weekend
0 2024-01-15  2024      1   15        0         No
1 2024-03-20  2024      3   20        2         No

#Log Transformation

In [ ]:
# used for highly skewed data

In [ ]:
import numpy as np
salary = np.array([
    30000,
    40000,
    50000,
    1000000
])

# Log transformation reduces the effect of the extreme values

# log(10^3) = 3
# log(10^10) = 10


log_salary = np.log(salary)
log_salary

array([10.30895266, 10.59663473, 10.81977828, 13.81551056])

#Mini-Casestudy

In [ ]:
df = pd.DataFrame({
    "Age":[25,35,45],
    "Income":[50000,80000,100000],
    "Orders":[10,20,40]
})

In [ ]:
df

   Age  Income  Orders
0   25   50000      10
1   35   80000      20
2   45  100000      40

In [ ]:
# 1. income per order
df["income_per_order"] = df["Income"]/df["Orders"]

In [ ]:
df

   Age  Income  Orders  income_per_order
0   25   50000      10            5000.0
1   35   80000      20            4000.0
2   45  100000      40            2500.0

In [ ]:
# 2. Above_avg --> if income is greater than the avg income of all the customers.

avg_income = df["Income"].mean()

df["above_avg"] = df["Income"] > avg_income
df

   Age  Income  Orders  income_per_order  above_avg
0   25   50000      10            5000.0      False
1   35   80000      20            4000.0       True
2   45  100000      40            2500.0       True

In [ ]:
# 3. create age group bucket.

df["age_group"] = pd.cut(df["Age"],
                         bins=[0,18,60,100],
                        labels=["Kid", "Adult", "Senior"]
                         )
df

   Age  Income  Orders  income_per_order  above_avg age_group
0   25   50000      10            5000.0      False     Adult
1   35   80000      20            4000.0       True     Adult
2   45  100000      40            2500.0       True     Adult

In [ ]:
# 4. Scaled Salary --> Min-Max Scaling
df.describe()

        Age         Income     Orders  income_per_order
count   3.0       3.000000   3.000000          3.000000
mean   35.0   76666.666667  23.333333       3833.333333
std    10.0   25166.114784  15.275252       1258.305739
min    25.0   50000.000000  10.000000       2500.000000
25%    30.0   65000.000000  15.000000       3250.000000
50%    35.0   80000.000000  20.000000       4000.000000
75%    40.0   90000.000000  30.000000       4500.000000
max    45.0  100000.000000  40.000000       5000.000000

In [ ]:
min_max_sc = MinMaxScaler()

df["min_max_income"] = min_max_sc.fit_transform(df[["Income"]])
df

   Age  Income  Orders  income_per_order  above_avg age_group  min_max_income
0   25   50000      10            5000.0      False     Adult             0.0
1   35   80000      20            4000.0       True     Adult             0.6
2   45  100000      40            2500.0       True     Adult             1.0

In [ ]:
# 5 -> Standard scaling over income

std_sc = StandardScaler()

df["std_scaled_income"] = std_sc.fit_transform(df[["Income"]])

In [ ]:
df

,Age,Income,Orders,income_per_order,above_avg,age_group,min_max_income,std_scaled_income
0,25,50000,10,5000.0,False,Adult,0.0,-1.297771
1,35,80000,20,4000.0,True,Adult,0.6,0.162221
2,45,100000,40,2500.0,True,Adult,1.0,1.135550

In [ ]:
#Which algorithms require Scaling?

# 1. KNN -> K Nearest Neighbors
# 2. SVM --> Support Vector Machine
# 3. K- Means -->
# 4. PCA --> Principal Component Analysis
# 5. Logistic Regression.