<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/module3/M3C5%20Feature%20Scaling%20and%20Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome friends!!")

Welcome friends!!

In [ ]:
#House Price Prediction:

Features: sqft area, locality, bhk, aminites, etc ---> independent variables
Target variable - price -> dependent variable

In [ ]:
Algorithms that need feature scaling to perform accurately:

1. KNN -> K nearest neighbors
2. K-means --> Clustering
3. SVM --> Support Vector Machine
4. Logistic Regression --> Classification
5. Linear Regression --> usually yes --> Regression
6. PCA --> Principal Component Analysis --> Dimensionality Reduction

Algorithms that are not impacted due to feature scaling:
1. Decision Trees.
2. Random Forget
3. XGBoost

In [ ]:
In tree based algos, feature scaling is not mandatory --> as the split remains exactly the same.

salary: 100k - 500k
rescale : 1 - 5

salary > 250k
salary > 2.5

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "marks" :  [40, 60, 80, 100]
})

In [ ]:
df

   marks
0     40
1     60
2     80
3    100

#Min-Max Scaling (0 to 1) --> Normalization: transforming the data into a fixed range.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mn_mx_sc = MinMaxScaler()

df["Min_Max_Marks"] = mn_mx_sc.fit_transform(df[["marks"]])
df

   marks  Min_Max_Marks
0     40       0.000000
1     60       0.333333
2     80       0.666667
3    100       1.000000

#Standardization: Mean = 0, Std = 1

In [ ]:
from sklearn.preprocessing import StandardScaler

std_sc = StandardScaler()
df["std_sc_marks"] = std_sc.fit_transform(df[["marks"]])
df

   marks  Min_Max_Marks  std_sc_marks
0     40       0.000000     -1.341641
1     60       0.333333     -0.447214
2     80       0.666667      0.447214
3    100       1.000000      1.341641

#Which to use when?

In [ ]:
# Use Min-Max Scaler: (Normalization)

# 1. want the feature values to fall in a specific range( usually between 0 to 1)
# 2. When we need bounded inputs: essential for neural networks and for distance based algos like: KNN and K-means
# 3. when known meaningful limits exist --> for image processing: pixels ( 0 to 255), percentages ( 0 to 100), probabilityL: (0 to 1)
# 4. When the data is not normally distributed. --> min max scaler preserves the shape of the original distribution.

In [ ]:
# Use Standard Scaler (Standardization):
# 1. Works the best when the data is normally distributed (follows bell curve)
# 2. for Linear models and PCA --> Linear regression, logistic regression, SVM, PCA


# Imp note: When there is presence of outliers, both scalers might fail as they both are sensitive to outliers.
# eg: (1,2,3,4, 10000). In this case, when outliers are present, we prefer RobustScaler.

In [ ]:
df = pd.DataFrame({
    "Age" : [20,30,40],
    "Salary": [30000, 50000, 100000]
})

df

   Age  Salary
0   20   30000
1   30   50000
2   40  100000

In [ ]:
sc = StandardScaler()

scaled = sc.fit_transform(df)
scaled_df = pd.DataFrame(scaled, columns = df.columns)

scaled_df

        Age    Salary
0 -1.224745 -1.019049
1  0.000000 -0.339683
2  1.224745  1.358732

In [ ]:
df

   Age  Salary
0   20   30000
1   30   50000
2   40  100000

In [ ]:
sc = MinMaxScaler()

scaled = sc.fit_transform(df)
mn_mx_df = pd.DataFrame(scaled, columns = df.columns)

mn_mx_df

   Age    Salary
0  0.0  0.000000
1  0.5  0.285714
2  1.0  1.000000

In [ ]:
scaled_df

        Age    Salary
0 -1.224745 -1.019049
1  0.000000 -0.339683
2  1.224745  1.358732

#Data Leakage

In [ ]:
# Never learn scaling parameters from the test data. Only use the training data to learn the scaler parameters.

# app1: data --> scaling --> train test split  --> data leakage
# app2: data --> train test split --> scaling --> correct

In [ ]:
df = pd.DataFrame({
    "Age":[20,25,30,35],
    "Salary":[30000,35000,90000,95000],
    "Approved":[0,0,1,1]
})

x = df[["Age", "Salary"]]
y = df["Approved"]

x

   Age  Salary
0   20   30000
1   25   35000
2   30   90000
3   35   95000

In [ ]:
y

0    0
1    0
2    1
3    1
Name: Approved, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
                                                      x,
                                                      y,
                                                      test_size = 0.2,
                                                      random_state = 45)


sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

   Age  Salary
1   25   35000
2   30   90000
3   35   95000

In [ ]:
x_test

   Age  Salary
0   20   30000

In [ ]:
y_train

1    0
2    1
3    1
Name: Approved, dtype: int64

In [ ]:
y_test

0    0
Name: Approved, dtype: int64

#RobustScaler

In [ ]:
import numpy as np
salary = np.array([10000, 20000, 35000, 42000, 600000]).reshape(-1,1)

sc = MinMaxScaler()
mn_salary = sc.fit_transform(salary)

In [ ]:
mn_salary

array([[0.        ],
       [0.01694915],
       [0.04237288],
       [0.05423729],
       [1.        ]])

In [ ]:
from sklearn.preprocessing import RobustScaler

sc = RobustScaler()
r_scaled = sc.fit_transform(salary)

In [ ]:
r_scaled

array([[-1.13636364],
       [-0.68181818],
       [ 0.        ],
       [ 0.31818182],
       [25.68181818]])

In [ ]:
# Instead of mean --> it uses median
# Instead of standard deviation --> it uses interquartile range (IQR)


# Hence it is less effected by outliers.