<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/module3/M3C6%20End%20to%20End%20Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pipeline

In [ ]:
| Name | Salary | Age | Purchased |
| ---- | ------ | --- | --------- |
| A    | 40000  | 25  | Yes       |
| B    | ?      | 30  | No        |
| C    | 70000  |     | Yes       |

#ML Pipeline

In [ ]:
1. Raw data
2. Cleaning & Pre-processing --> most important step
3. Feature Engineering
4. Training
5. Evaluation
6. Deployment

#What is the purpose of each of the step?

In [ ]:
1.Data collection --> What information do we have?
2. Exploring the data --> What does the data look like?
3. Clean data --> is the data ready to be used?
4. Feature Engineering --> Can we further enhance the quality of the data?
5. Training the model --> learning the patterns present in the data.
6. Evaluation --> is the model relaible?
7. Deployment --> making it useful for the target audience.
8. Monitor --> Is everything on track? Any updates needed?

#Importance of Every step

In [ ]:
What happens if we skip:

1. Data collection: No data to learn from
2. Cleaning & Pre-processing --> garbage in, garbage out
3. Feature Engineering --> some algos will perform poor
4. Training --> bad performance on the test data.
5. Evaluation --> no clarity and awareness about the quality of the model
6. Deployment --> model becomes outdated and not useful.

#Collection Data

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID":[101,102,103,104,105,106,107,108,109,110],

    "Gender":[
        "Male","Female","Female","Male","Male",
        "Female","Male","Female","Male","Female"
    ],

    "Department":[
        "CS","IT","CS","ECE","IT",
        "CS","ECE","IT","CS","ECE"
    ],

    "Study_Hours":[
        2,5,7,3,8,
        6,4,9,np.nan,5
    ],

    "Attendance":[
        60,82,91,70,95,
        88,75,98,80,np.nan
    ],

    "Assignments":[
        3,7,8,5,9,
        8,6,10,7,6
    ],

    "Previous_Score":[
        55,72,85,60,90,
        82,65,95,78,70
    ],

    "Sports":[
        "Yes","No","No","Yes","No",
        "No","Yes","No","Yes","No"
    ],

    "Pass":[
        0,1,1,0,1,
        1,0,1,1,0
    ]
})

print(df)

   Student_ID  Gender Department  Study_Hours  Attendance  Assignments  \
0         101    Male         CS          2.0        60.0            3
1         102  Female         IT          5.0        82.0            7
2         103  Female         CS          7.0        91.0            8
3         104    Male        ECE          3.0        70.0            5
4         105    Male         IT          8.0        95.0            9
5         106  Female         CS          6.0        88.0            8
6         107    Male        ECE          4.0        75.0            6
7         108  Female         IT          9.0        98.0           10
8         109    Male         CS          NaN        80.0            7
9         110  Female        ECE          5.0         NaN            6

   Previous_Score Sports  Pass
0              55    Yes     0
1              72     No     1
2              85     No     1
3              60    Yes     0
4              90     No     1
5              82     No     1
6              65    Yes     0
7              95     No     1
8              78    Yes     1
9              70     No     0

In [ ]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.0,60.0,3,55,Yes,0
1,102,Female,IT,5.0,82.0,7,72,No,1
2,103,Female,CS,7.0,91.0,8,85,No,1
3,104,Male,ECE,3.0,70.0,5,60,Yes,0
4,105,Male,IT,8.0,95.0,9,90,No,1
5,106,Female,CS,6.0,88.0,8,82,No,1
6,107,Male,ECE,4.0,75.0,6,65,Yes,0
7,108,Female,IT,9.0,98.0,10,95,No,1
8,109,Male,CS,NaN,80.0,7,78,Yes,1
9,110,Female,ECE,5.0,NaN,6,70,No,0

#Understanding the data - EDA

In [ ]:
df.shape

(10, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      10 non-null     int64
 1   Gender          10 non-null     object
 2   Department      10 non-null     object
 3   Study_Hours     9 non-null      float64
 4   Attendance      9 non-null      float64
 5   Assignments     10 non-null     int64
 6   Previous_Score  10 non-null     int64
 7   Sports          10 non-null     object
 8   Pass            10 non-null     int64
dtypes: float64(2), int64(4), object(3)
memory usage: 852.0+ bytes

In [ ]:
df.describe()

,Student_ID,Study_Hours,Attendance,Assignments,Previous_Score,Pass
count,10.00000,9.000000,9.000000,10.000000,10.000000,10.000000
mean,105.50000,5.444444,82.111111,6.900000,75.200000,0.600000
std,3.02765,2.297341,12.363701,2.024846,13.087738,0.516398
min,101.00000,2.000000,60.000000,3.000000,55.000000,0.000000
25%,103.25000,4.000000,75.000000,6.000000,66.250000,0.000000
50%,105.50000,5.000000,82.000000,7.000000,75.000000,1.000000
75%,107.75000,7.000000,91.000000,8.000000,84.250000,1.000000
max,110.00000,9.000000,98.000000,10.000000,95.000000,1.000000

#Data Cleaning

In [ ]:
# 1. Identifying the missing data
# 2. Filling the mising data
# 3. Identify and remove the duplicate rows/data
# 4. Handle incorrect datatypes
# 5. Remove outliers.

In [ ]:
df.isnull().sum()

Student_ID        0
Gender            0
Department        0
Study_Hours       1
Attendance        1
Assignments       0
Previous_Score    0
Sports            0
Pass              0
dtype: int64

In [ ]:
df["Study_Hours"] = df["Study_Hours"].fillna(df["Study_Hours"].mean())

In [ ]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.000000,60.0,3,55,Yes,0
1,102,Female,IT,5.000000,82.0,7,72,No,1
2,103,Female,CS,7.000000,91.0,8,85,No,1
3,104,Male,ECE,3.000000,70.0,5,60,Yes,0
4,105,Male,IT,8.000000,95.0,9,90,No,1
5,106,Female,CS,6.000000,88.0,8,82,No,1
6,107,Male,ECE,4.000000,75.0,6,65,Yes,0
7,108,Female,IT,9.000000,98.0,10,95,No,1
8,109,Male,CS,5.444444,80.0,7,78,Yes,1
9,110,Female,ECE,5.000000,NaN,6,70,No,0

In [ ]:
female_df = df[df["Gender"] == "Female"]
female_df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
1,102,Female,IT,5.0,82.0,7,72,No,1
2,103,Female,CS,7.0,91.0,8,85,No,1
5,106,Female,CS,6.0,88.0,8,82,No,1
7,108,Female,IT,9.0,98.0,10,95,No,1
9,110,Female,ECE,5.0,NaN,6,70,No,0

In [ ]:
avg_female_attendance = female_df["Attendance"].mean()
avg_female_attendance

np.float64(89.75)

In [ ]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.000000,60.000000,3,55,Yes,0
1,102,Female,IT,5.000000,82.000000,7,72,No,1
2,103,Female,CS,7.000000,91.000000,8,85,No,1
3,104,Male,ECE,3.000000,70.000000,5,60,Yes,0
4,105,Male,IT,8.000000,95.000000,9,90,No,1
5,106,Female,CS,6.000000,88.000000,8,82,No,1
6,107,Male,ECE,4.000000,75.000000,6,65,Yes,0
7,108,Female,IT,9.000000,98.000000,10,95,No,1
8,109,Male,CS,5.444444,80.000000,7,78,Yes,1
9,110,Female,ECE,5.000000,82.111111,6,70,No,0

In [ ]:
df["Attendance"] = df["Attendance"].fillna(avg_female_attendance)

In [ ]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.000000,60.00,3,55,Yes,0
1,102,Female,IT,5.000000,82.00,7,72,No,1
2,103,Female,CS,7.000000,91.00,8,85,No,1
3,104,Male,ECE,3.000000,70.00,5,60,Yes,0
4,105,Male,IT,8.000000,95.00,9,90,No,1
5,106,Female,CS,6.000000,88.00,8,82,No,1
6,107,Male,ECE,4.000000,75.00,6,65,Yes,0
7,108,Female,IT,9.000000,98.00,10,95,No,1
8,109,Male,CS,5.444444,80.00,7,78,Yes,1
9,110,Female,ECE,5.000000,89.75,6,70,No,0

In [ ]:
df["hours_per_assign"] = df["Study_Hours"]/df["Assignments"]
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass,hours_per_assign
0,101,Male,CS,2.000000,60.00,3,55,Yes,0,0.666667
1,102,Female,IT,5.000000,82.00,7,72,No,1,0.714286
2,103,Female,CS,7.000000,91.00,8,85,No,1,0.875000
3,104,Male,ECE,3.000000,70.00,5,60,Yes,0,0.600000
4,105,Male,IT,8.000000,95.00,9,90,No,1,0.888889
5,106,Female,CS,6.000000,88.00,8,82,No,1,0.750000
6,107,Male,ECE,4.000000,75.00,6,65,Yes,0,0.666667
7,108,Female,IT,9.000000,98.00,10,95,No,1,0.900000
8,109,Male,CS,5.444444,80.00,7,78,Yes,1,0.777778
9,110,Female,ECE,5.000000,89.75,6,70,No,0,0.833333

In [ ]:
x  = df[["Student_ID", "Gender", "Department", "Study_Hours", "Attendance"]]
x

   Student_ID  Gender Department  Study_Hours  Attendance
0         101    Male         CS     2.000000       60.00
1         102  Female         IT     5.000000       82.00
2         103  Female         CS     7.000000       91.00
3         104    Male        ECE     3.000000       70.00
4         105    Male         IT     8.000000       95.00
5         106  Female         CS     6.000000       88.00
6         107    Male        ECE     4.000000       75.00
7         108  Female         IT     9.000000       98.00
8         109    Male         CS     5.444444       80.00
9         110  Female        ECE     5.000000       89.75

In [ ]:
x = df.drop(columns = ["Pass"])
x

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,hours_per_assign
0,101,Male,CS,2.000000,60.00,3,55,Yes,0.666667
1,102,Female,IT,5.000000,82.00,7,72,No,0.714286
2,103,Female,CS,7.000000,91.00,8,85,No,0.875000
3,104,Male,ECE,3.000000,70.00,5,60,Yes,0.600000
4,105,Male,IT,8.000000,95.00,9,90,No,0.888889
5,106,Female,CS,6.000000,88.00,8,82,No,0.750000
6,107,Male,ECE,4.000000,75.00,6,65,Yes,0.666667
7,108,Female,IT,9.000000,98.00,10,95,No,0.900000
8,109,Male,CS,5.444444,80.00,7,78,Yes,0.777778
9,110,Female,ECE,5.000000,89.75,6,70,No,0.833333

In [ ]:
y = df["Pass"]

In [ ]:
y

0    0
1    1
2    1
3    0
4    1
5    1
6    0
7    1
8    1
9    0
Name: Pass, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
 x,
 y,
 test_size = 0.3,
 random_state = 42
)

In [ ]:
x_train

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,hours_per_assign
0,101,Male,CS,2.0,60.00,3,55,Yes,0.666667
7,108,Female,IT,9.0,98.00,10,95,No,0.900000
2,103,Female,CS,7.0,91.00,8,85,No,0.875000
9,110,Female,ECE,5.0,89.75,6,70,No,0.833333
4,105,Male,IT,8.0,95.00,9,90,No,0.888889
3,104,Male,ECE,3.0,70.00,5,60,Yes,0.600000
6,107,Male,ECE,4.0,75.00,6,65,Yes,0.666667

In [ ]:
x_test

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,hours_per_assign
8,109,Male,CS,5.444444,80.0,7,78,Yes,0.777778
1,102,Female,IT,5.000000,82.0,7,72,No,0.714286
5,106,Female,CS,6.000000,88.0,8,82,No,0.750000

In [ ]:
y_train

0    0
7    1
2    1
9    0
4    1
3    0
6    0
Name: Pass, dtype: int64

In [ ]:
y_test

8    1
1    1
5    1
Name: Pass, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

# model.fit(x_train, x_test)

In [ ]:
model.predict([[]])