<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/module3/M3C7%20Data%20Splitting%20%26%20Validation%20Protocol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Friends!!")

Hello Friends!!

In [ ]:
# | Hours | Marks |
# | ----- | ----- |
# | 1     | 20    |
# | 2     | 35    |
# | 3     | 45    |
# | 4     | 60    |
# | 5     | 75    |

#Generalization

In [ ]:
# #Performing well on the unseen data and not just on the training data.
# Model1:
# Training data accuracy = 99%
# but test data accuracy = 60%

# When the model performs excellent on the training data but does not perform well on the test data.
# This is called overfitting problem.

In [ ]:
# Model2:

# Training - 98%
# test data - 95%

# This is a better model

#Train Test Split

In [ ]:
# 100 rows

# train -> 80 rows
# test -> 20 rows

# Training data --> teaching model the patterns
# test data --> evaluating the quality of the model.

In [ ]:
import pandas as pd

students = pd.DataFrame({
    "Hours" : [1,2,3,4,5,6,7,8],
    "Marks" : [20,30,40,50,60,70,80,90]
})

students

   Hours  Marks
0      1     20
1      2     30
2      3     40
3      4     50
4      5     60
5      6     70
6      7     80
7      8     90

In [ ]:
x = students[["Hours"]]
y = students["Marks"]

In [ ]:
x

   Hours
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8

In [ ]:
y

0    20
1    30
2    40
3    50
4    60
5    70
6    80
7    90
Name: Marks, dtype: int64

In [ ]:
x.size

8

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

In [ ]:
x_train

   Hours
0      1
7      8
2      3
4      5
3      4
6      7

In [ ]:
y_train

0    20
7    90
2    40
4    60
3    50
6    80
Name: Marks, dtype: int64

In [ ]:
x_test

   Hours
1      2
5      6

In [ ]:
y_test

1    30
5    70
Name: Marks, dtype: int64

In [ ]:
# #data --> 500 rows, test_size = 0.1, training data?

# 10% of the data --> testing --> 50 rows
# 90% of the data --> training --> 450 rows

#Use case of random_state

In [ ]:
from sklearn.model_selection import train_test_split

x_train1, x_test1, y_train1, y_test1 = train_test_split(
    x,
    y,
    test_size = 0.2
)

In [ ]:
x_train1

   Hours
3      4
0      1
2      3
6      7
7      8
4      5

#Validation Set

In [ ]:
# Eg:

# train --> 70%
# validation -> 15%
# test -> 15%

In [ ]:
#purpose of each one of them:

1. Training data --> model learns the patterns
2. Validation data --> Hyperparameter tuning
3. Test data --> Evaluating the performance of the model.


Study --> mock test --> final exam

train --> validation --> test

In [ ]:
# train - 70%
# validation - 15%
# test - 15%

In [ ]:
# Idea:

# # 100 rows --> split(30%)a
# training rows = 70,
# temp rows = 30 --> split(50%) --> 15 validation, 15 test.

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_temp, y_train, y_temp = train_test_split(
    x,
    y,
    test_size = 0.3,
    random_state = 42)

In [ ]:
x_val, x_test, y_val, y_test = train_test_split(
    x_temp,
    y_temp,
    test_size = 0.5,
    random_state=  42
)

In [ ]:
x_train, x_test, x_val

(   Hours
 7      8
 2      3
 4      5
 3      4
 6      7,
    Hours
 1      2
 5      6,
    Hours
 0      1)

In [ ]:
y_train, y_test, y_val

(7    90
 2    40
 4    60
 3    50
 6    80
 Name: Marks, dtype: int64,
 1    30
 5    70
 Name: Marks, dtype: int64,
 0    20
 Name: Marks, dtype: int64)

In [ ]:
y_test

1    30
5    70
Name: Marks, dtype: int64

In [ ]:
y_train

7    90
2    40
4    60
3    50
6    80
Name: Marks, dtype: int64

In [ ]:
y_val

0    20
Name: Marks, dtype: int64

#ML Pipeline (Complete workflow)

In [ ]:
# 1. Problem Statement.
# 2. Data Collection
# 3. Data cleaning & preprocessing
# 4. EDA
# 5. Feature Scaling
# 6. Feature Engineering
# 7. Train-test-validation splitting
# 8. Model Training
# 9. Validation
# 10. Retraining
# 11. Final testing
# 12. Deployment
# 13. Monitoring

#Most common Splitting ratios: (in general, not fixed)

In [ ]:
# 1. Very small dataset --> train  - 90, test - 10
# 2. Medium --> train - 80, test - 20
# 3. large -->  train - 70, validation - 15, test - 15
# 4. Very large -> train - 60, validation - 20 , test - 20



100 -> 70% --> 70

1000--> 60%--> 600