<a href="https://colab.research.google.com/github/sunil965/masai-aiml/blob/module3/M3C8%20Integrated%20Data%20Preperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Friends!!")

Hello Friends!!

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({

       "Student_ID":[101,102,103,104,105,106,107,108,109,110],
        "Gender":[
        "Male","Female","Male","Female",
        "Male","Female","Male","Female",
        "Male","Male"
    ],

         "City":[
        "Delhi","Mumbai","Pune","Delhi",
        "Pune","Mumbai","Delhi","Pune",
        "Mumbai","Delhi"
    ],

      "Age":[20,21,19,np.nan,22,20,21,23,np.nan,20],

         "Hours_Studied":[
        2,5,4,6,3,7,5,8,4,6
    ],

       "Attendance":[
        80,92,88,95,75,98,90,96,84,91
    ],


           "Previous_Marks":[
        60,75,68,82,55,90,76,89,70,80
    ],


    "Placement":[
        "No","Yes","No","Yes",
        "No","Yes","Yes","Yes",
        "No","Yes"
    ]

})

df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20.0,2,80,60,No
1,102,Female,Mumbai,21.0,5,92,75,Yes
2,103,Male,Pune,19.0,4,88,68,No
3,104,Female,Delhi,NaN,6,95,82,Yes
4,105,Male,Pune,22.0,3,75,55,No
5,106,Female,Mumbai,20.0,7,98,90,Yes
6,107,Male,Delhi,21.0,5,90,76,Yes
7,108,Female,Pune,23.0,8,96,89,Yes
8,109,Male,Mumbai,NaN,4,84,70,No
9,110,Male,Delhi,20.0,6,91,80,Yes

In [ ]:
# features: student_id, gender, city, age, hours_studied, attendance, prev_marks

# target: Placement

# Numerical? --> age, hours_studied, attendance, prev_marks
# Categorical --> city, gender

# Column identifier --> student_id  --> not a real feature as doesnt help in prediction.

#EDA

In [ ]:
df.head()

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20.0,2,80,60,No
1,102,Female,Mumbai,21.0,5,92,75,Yes
2,103,Male,Pune,19.0,4,88,68,No
3,104,Female,Delhi,NaN,6,95,82,Yes
4,105,Male,Pune,22.0,3,75,55,No

In [ ]:
df.shape

(10, 8)

In [ ]:
df.columns

Index(['Student_ID', 'Gender', 'City', 'Age', 'Hours_Studied', 'Attendance',
       'Previous_Marks', 'Placement'],
      dtype='object')

In [ ]:
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20.0,2,80,60,No
1,102,Female,Mumbai,21.0,5,92,75,Yes
2,103,Male,Pune,19.0,4,88,68,No
3,104,Female,Delhi,NaN,6,95,82,Yes
4,105,Male,Pune,22.0,3,75,55,No
5,106,Female,Mumbai,20.0,7,98,90,Yes
6,107,Male,Delhi,21.0,5,90,76,Yes
7,108,Female,Pune,23.0,8,96,89,Yes
8,109,Male,Mumbai,NaN,4,84,70,No
9,110,Male,Delhi,20.0,6,91,80,Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      10 non-null     int64
 1   Gender          10 non-null     object
 2   City            10 non-null     object
 3   Age             8 non-null      float64
 4   Hours_Studied   10 non-null     int64
 5   Attendance      10 non-null     int64
 6   Previous_Marks  10 non-null     int64
 7   Placement       10 non-null     object
dtypes: float64(1), int64(4), object(3)
memory usage: 772.0+ bytes

In [ ]:
df.describe()

       Student_ID       Age  Hours_Studied  Attendance  Previous_Marks
count    10.00000   8.00000      10.000000   10.000000       10.000000
mean    105.50000  20.75000       5.000000   88.900000       74.500000
std       3.02765   1.28174       1.825742    7.324995       11.510864
min     101.00000  19.00000       2.000000   75.000000       55.000000
25%     103.25000  20.00000       4.000000   85.000000       68.500000
50%     105.50000  20.50000       5.000000   90.500000       75.500000
75%     107.75000  21.25000       6.000000   94.250000       81.500000
max     110.00000  23.00000       8.000000   98.000000       90.000000

In [ ]:
df.isnull()

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Student_ID        0
Gender            0
City              0
Age               2
Hours_Studied     0
Attendance        0
Previous_Marks    0
Placement         0
dtype: int64

#Handling missing data

In [ ]:
# drop --> leads to loss of data
# impute --> fillna() --> replace it with some relevant data

In [ ]:
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20.0,2,80,60,No
1,102,Female,Mumbai,21.0,5,92,75,Yes
2,103,Male,Pune,19.0,4,88,68,No
3,104,Female,Delhi,NaN,6,95,82,Yes
4,105,Male,Pune,22.0,3,75,55,No
5,106,Female,Mumbai,20.0,7,98,90,Yes
6,107,Male,Delhi,21.0,5,90,76,Yes
7,108,Female,Pune,23.0,8,96,89,Yes
8,109,Male,Mumbai,NaN,4,84,70,No
9,110,Male,Delhi,20.0,6,91,80,Yes

In [ ]:
avg_age = df["Age"].mean()
avg_age

np.float64(20.75)

In [ ]:
df["Age"] = df["Age"].fillna(avg_age)

In [ ]:
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20.00,2,80,60,No
1,102,Female,Mumbai,21.00,5,92,75,Yes
2,103,Male,Pune,19.00,4,88,68,No
3,104,Female,Delhi,20.75,6,95,82,Yes
4,105,Male,Pune,22.00,3,75,55,No
5,106,Female,Mumbai,20.00,7,98,90,Yes
6,107,Male,Delhi,21.00,5,90,76,Yes
7,108,Female,Pune,23.00,8,96,89,Yes
8,109,Male,Mumbai,20.75,4,84,70,No
9,110,Male,Delhi,20.00,6,91,80,Yes

In [ ]:
# eg2: salary: 10000, 15000, 20000, 17000, 1000000

# better choice --> median.

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df2 = pd.DataFrame({


        "Gender":[
        "Male","Female","Male","Female",
        "Male","Female","Male","Female",
        "Male","Male"
    ],

         "City":[
        "Delhi","Mumbai","Delhi","Delhi",
        "Pune","Mumbai","Delhi","Pune",
        "Mumbai","Delhi"
    ]
})

In [ ]:
df2

   Gender    City
0    Male   Delhi
1  Female  Mumbai
2    Male   Delhi
3  Female   Delhi
4    Male    Pune
5  Female  Mumbai
6    Male   Delhi
7  Female    Pune
8    Male  Mumbai
9    Male   Delhi

In [ ]:
df2.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
6     True
7    False
8    False
9     True
dtype: bool

In [ ]:
df2.duplicated().sum()

np.int64(4)

In [ ]:
df2.drop_duplicates()

   Gender    City
0    Male   Delhi
1  Female  Mumbai
3  Female   Delhi
4    Male    Pune
7  Female    Pune
8    Male  Mumbai

In [ ]:
df2

   Gender    City
0    Male   Delhi
1  Female  Mumbai
2    Male   Delhi
3  Female   Delhi
4    Male    Pune
5  Female  Mumbai
6    Male   Delhi
7  Female    Pune
8    Male  Mumbai
9    Male   Delhi

In [ ]:
# df2.drop_duplicates(inplace = True)

In [ ]:
df2

   Gender    City
0    Male   Delhi
1  Female  Mumbai
2    Male   Delhi
3  Female   Delhi
4    Male    Pune
5  Female  Mumbai
6    Male   Delhi
7  Female    Pune
8    Male  Mumbai
9    Male   Delhi

In [ ]:
df3 = df2.drop_duplicates()
df3

   Gender    City
0    Male   Delhi
1  Female  Mumbai
3  Female   Delhi
4    Male    Pune
7  Female    Pune
8    Male  Mumbai

In [ ]:
df2

   Gender    City
0    Male   Delhi
1  Female  Mumbai
2    Male   Delhi
3  Female   Delhi
4    Male    Pune
5  Female  Mumbai
6    Male   Delhi
7  Female    Pune
8    Male  Mumbai
9    Male   Delhi

In [ ]:
df4 = df2.drop_duplicates(inplace = True)

In [ ]:
df4

In [ ]:
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20.00,2,80,60,No
1,102,Female,Mumbai,21.00,5,92,75,Yes
2,103,Male,Pune,19.00,4,88,68,No
3,104,Female,Delhi,20.75,6,95,82,Yes
4,105,Male,Pune,22.00,3,75,55,No
5,106,Female,Mumbai,20.00,7,98,90,Yes
6,107,Male,Delhi,21.00,5,90,76,Yes
7,108,Female,Pune,23.00,8,96,89,Yes
8,109,Male,Mumbai,20.75,4,84,70,No
9,110,Male,Delhi,20.00,6,91,80,Yes

In [ ]:
df["Age"] = df["Age"].astype(int)

In [ ]:
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement
0,101,Male,Delhi,20,2,80,60,No
1,102,Female,Mumbai,21,5,92,75,Yes
2,103,Male,Pune,19,4,88,68,No
3,104,Female,Delhi,20,6,95,82,Yes
4,105,Male,Pune,22,3,75,55,No
5,106,Female,Mumbai,20,7,98,90,Yes
6,107,Male,Delhi,21,5,90,76,Yes
7,108,Female,Pune,23,8,96,89,Yes
8,109,Male,Mumbai,20,4,84,70,No
9,110,Male,Delhi,20,6,91,80,Yes

In [ ]:
df["Attendance"].mean()

np.float64(88.9)

In [ ]:
df["Previous_Marks"].max()

90

In [ ]:
df["Hours_Studied"].value_counts()

Hours_Studied
5    2
4    2
6    2
2    1
3    1
7    1
8    1
Name: count, dtype: int64

In [ ]:
df["Gender"].value_counts()

Gender
Male      6
Female    4
Name: count, dtype: int64

In [ ]:
df["Gender"].value_counts(normalize = True)

Gender
Male      0.6
Female    0.4
Name: proportion, dtype: float64

In [ ]:
df["City"].value_counts(normalize = True)

City
Delhi     0.4
Mumbai    0.3
Pune      0.3
Name: proportion, dtype: float64

In [ ]:
# Q. For each city, what are the avg number of hours students study?


df.groupby("City")["Hours_Studied"].mean()

City
Delhi     4.750000
Mumbai    5.333333
Pune      5.000000
Name: Hours_Studied, dtype: float64

In [ ]:
df.groupby("Gender")["Attendance"].mean()

Gender
Female    95.250000
Male      84.666667
Name: Attendance, dtype: float64

In [ ]:
df["Study_efficiency"] = df["Previous_Marks"]/df["Hours_Studied"]
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement,Study_efficiency
0,101,Male,Delhi,20,2,80,60,No,30.000000
1,102,Female,Mumbai,21,5,92,75,Yes,15.000000
2,103,Male,Pune,19,4,88,68,No,17.000000
3,104,Female,Delhi,20,6,95,82,Yes,13.666667
4,105,Male,Pune,22,3,75,55,No,18.333333
5,106,Female,Mumbai,20,7,98,90,Yes,12.857143
6,107,Male,Delhi,21,5,90,76,Yes,15.200000
7,108,Female,Pune,23,8,96,89,Yes,11.125000
8,109,Male,Mumbai,20,4,84,70,No,17.500000
9,110,Male,Delhi,20,6,91,80,Yes,13.333333

In [ ]:
#Creat a new feature - "High_Attendance" --> True if attendance atleast 85, else False.

df["High_Attendance"] = df["Attendance"] >= 85

In [ ]:
df

,Student_ID,Gender,City,Age,Hours_Studied,Attendance,Previous_Marks,Placement,Study_efficiency,High_Attendance
0,101,Male,Delhi,20,2,80,60,No,30.000000,False
1,102,Female,Mumbai,21,5,92,75,Yes,15.000000,True
2,103,Male,Pune,19,4,88,68,No,17.000000,True
3,104,Female,Delhi,20,6,95,82,Yes,13.666667,True
4,105,Male,Pune,22,3,75,55,No,18.333333,False
5,106,Female,Mumbai,20,7,98,90,Yes,12.857143,True
6,107,Male,Delhi,21,5,90,76,Yes,15.200000,True
7,108,Female,Pune,23,8,96,89,Yes,11.125000,True
8,109,Male,Mumbai,20,4,84,70,No,17.500000,False
9,110,Male,Delhi,20,6,91,80,Yes,13.333333,True